spring:
  #thymeleaf配置
  thymeleaf:
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.114.100:3306/testdb
    username: root
    password: jhkd5960795.
    hikari:
#      连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #最大空闲连接时间
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #连接最大存活时间
      max-lifetime: 1800000
      #连接超时时间
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#Mybatis plus配置
mybatis-plus:
  #配置映射的mapper文件
  mapper-locations: classpath*:mapper/*mapper.xml
  #配置返回数据类型的别名
  type-aliases-package: com.jayczee.pojo

#Mybatis-plus日志打印
logging:
  level:
    com.jayczee.mapper: debug

